FROM amazonlinux:2023

RUN dnf install -y python3 python3-pip gcc g++ make libcurl-devel && \
    python3 -m ensurepip && \
    python3 -m pip install --no-cache-dir --upgrade pip --ignore-installed

# Copy and install dependencies

RUN echo $PIP_REQUIRE_HASHES

RUN python3 --version
COPY requirements.txt /tmp/requirements.txt
RUN pip3 install --no-cache-dir -r /tmp/requirements.txt --timeout 360 --retries 5 --prefer-binary

# Create a non-root user
RUN useradd -m -s /bin/bash jupyteruser

USER jupyteruser
WORKDIR /home/jupyteruser

CMD ["jupyter-lab", "--ip=0.0.0.0", "--no-browser"]